### ISSUE TITLE
Character Encoding Issue

### ISSUE THREAD

**Issue by tedchoward** [scripting/feeder#1]
It looks like there's a character encoding issue. I don't know if it's in this server module, or in the https://github.com/scripting/reallysimple module.

Here is a screenshot of the [NYTimes Theater Feed](http://feeder.scripting.com/returnjson?url=https://rss.nytimes.com/services/xml/rss/nyt/Theater.xml) on June 13, 2022 at 9:36am (CDT) as viewed by this app:
<img width="1466" alt="Screen Shot 2022-06-13 at 9 37 02 AM" src="https://user-images.githubusercontent.com/470549/173378528-1b5cc734-19bf-4801-83ea-427c4e66e9eb.png">

Note the title of the second item: `â€˜A Strange Loopâ€™ Wins Best Musical as Tonys Celebrate Broadwayâ€™s Return`

Here is a screenshot of second item in the [Feed](https://rss.nytimes.com/services/xml/rss/nyt/Theater.xml) as rendered by Firefox:
<img width="1298" alt="Screen Shot 2022-06-13 at 9 39 45 AM" src="https://user-images.githubusercontent.com/470549/173379159-94cc82fd-6921-4471-851e-58a8b4310d84.png">

Notice the *curly quotes* in the title: `‘A Strange Loop’ Wins Best Musical as Tonys Celebrate Broadway’s Return`

I haven't done any debugging myself, I just noticed it this morning when I clicked the [link from scripting.com](http://scripting.com/2022/06/12.html#a024939)

**Comment by scripting** [comment]
The problem should fixed in v0.4.5 of the feeder app, which is currently deployed.

http://feeder.scripting.com/returnjson?url=https://rss.nytimes.com/services/xml/rss/nyt/Theater.xml

http://feeder.scripting.com/returnopml?url=https://rss.nytimes.com/services/xml/rss/nyt/Theater.xml

**Comment by tedchoward** [comment]
Verified!
<img width="1285" alt="Screen Shot 2022-06-13 at 11 16 45 AM" src="https://user-images.githubusercontent.com/470549/173398572-c5066db7-bab0-42d9-a3f3-16a794357257.png">
